### ISSUE TITLE
文章中SDK压缩包无法正常解压

### ISSUE THREAD

**Issue by heiyebaitian** [awardat/ePass1000ND#1]
作者您好
在阅读您的文章时，下载到的SDK压缩包似乎无法正常解压，疑似是因为密码错误的原因，方便提供一下压缩包解压密码吗？不胜感激。

**Comment by awardat** [comment]
0FA.,5=UY}L.O~cV
我试了一下可以的，可能浏览器问题导致字符被替代了？

**Comment by heiyebaitian** [comment]
确实是这样 “}”被替代了，非常感谢！
